NightFairy/NightFairy/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index

urlpatterns = [
    path('', index, name= 'index'),
    path('main/', include('main.urls')),
    path('admin/', admin.site.urls),
]

NightFairy/main/urls.py
from django.urls import path
from .views import index, by_rubric, DbCreateView, product,delItem,pay, stocks, about_us, basket, cart, addToCart,plusNumber,minusNumber

app_name = 'main'
urlpatterns = [
	path('product/<int:product_id>/' , product, name = "product"),
	path('add/', DbCreateView.as_view(), name='add'),
	path('about_us/', about_us, name = 'about_us'),
	path('product/<int:product_id>/addToCart/', addToCart, name = 'addToCart'),
	path('makeComment/', basket, name = 'makeComment'),
	path('stocks/', stocks, name = 'stocks'),
	path('<int:rubric_id>/', by_rubric, name = 'by_rubric'),
	path('product/<int:product_id>/plus/', plusNumber, name = 'plusNumber'),
	path('product/<int:product_id>/minus/', minusNumber, name = 'minusNumber'),
	path('cart/', cart, name = 'cart'),
	path('product/<int:product_id>/del/', delItem, name = 'delItem'),
	path('', index, name = 'index'),
	path('pay/', pay, name = 'pay'),


]

NightFairy/cart/models.py
from django.db import models

# Create your models here.

NightFairy/main/models.py
from django.db import models

class Db(models.Model):
	title = models.CharField(max_length = 50, verbose_name = 'Название')
	content = models.TextField(null = True, blank = True, verbose_name = 'Краткое описание')
	full_content = models.TextField(null = True, blank = True, verbose_name = 'Полное Описание')
	price = models.FloatField(null = True, blank  = True, verbose_name = 'Цена')
	published = models.DateField(auto_now_add = True, db_index = True, verbose_name = 'Опубликовано')
	img_name = models.CharField(max_length = 100, verbose_name = 'Путь к изображению(src/photo.png)')
	rubric = models.ForeignKey('Rubric', null = True, on_delete = models.PROTECT, verbose_name = 'Рубрика')
	on_stock =models.BooleanField(default = False, blank = False, verbose_name = 'Есть ли акция?')
	stock_price = models.FloatField(null = True, blank  = True, verbose_name = 'Цена по акции')

	class Meta:
		verbose_name_plural = 'Обьявления'
		verbose_name = 'Обьявление'
		ordering = ['-published']
		
class Rubric(models.Model):
	name = models.CharField(max_length = 50, db_index = True, verbose_name = 'Название')

	def __str__(self):
		return self.name

	class Meta:
		verbose_name_plural = 'Рубрики'
		verbose_name = 'Рубрика'
		ordering = ['name']


NightFairy/main/forms.py
from django.forms import ModelForm

from .models import Db



class DbForm(ModelForm):
	class Meta:
		model = Db
		fields = ('title', 'content', 'price', 'rubric', 'img_name')

NightFairy/NightFairy/views.py
from django.shortcuts import redirect
def index(request):
	return redirect('/main/')

NightFairy/cart/views.py
from django.shortcuts import render

# Create your views here.

NightFairy/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.template import loader
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.core.exceptions import ObjectDoesNotExist
from array import *

from .models import Db, Rubric
from .forms import DbForm

class DbCreateView(CreateView):
	template_name = 'main/create.html'
	form_class = DbForm
	success_url = reverse_lazy('index')

	def get_context_date(self, **kwards):
		context = super().get_context_date(**kwards)
		context['rubrics'] = Rubric.objscts.all()

		return context

def delItem(request, product_id):
	sess = request.session['cart'].pop(str(product_id))
	request.session.modified = True


	return redirect('/main/cart/')
def by_rubric(request, rubric_id):
	dbs = Db.objects.filter(rubric=rubric_id)
	rubrics = Rubric.objects.all()
	current_rubric = Rubric.objects.get(pk = rubric_id)
	context = {'dbs':dbs, 'rubrics': rubrics, 'current_rubric': current_rubric}
	return render(request, 'main/by_rubric.html', context)

def product(request, product_id):
	try:
		db = Db.objects.get(id = product_id)
		rubrics = Rubric.objects.all()
		context = {'db': db, 'rubrics': rubrics}

	except ObjectDoesNotExist:
		raise Http404

	return render(request, 'main/product.html',context)

def addToCart(request, product_id):
	form = request.POST
	args = []
	if 'cart' in request.session:
		sess = request.session.get('cart')
		if str(product_id) not in sess:
			title=Db.objects.get(id = product_id).title

			if Db.objects.get(id = product_id).on_stock:
				price=Db.objects.get(id = product_id).stock_price	
			else:
				price=Db.objects.get(id = product_id).price

			args.insert(0,title)
			args.insert(1,price)
			args.insert(2, int(form['number']))
			sess[str(product_id)] = args
			request.session.modified = True

		else:
			title=Db.objects.get(id = product_id).title

			if Db.objects.get(id = product_id).on_stock:
				price=Db.objects.get(id = product_id).stock_price	
			else:
				price=Db.objects.get(id = product_id).price

			args.insert(0,title)
			args.insert(1,price)
			args.insert(2, int(sess[str(product_id)][2]) + int(form['number']))
			sess[str(product_id)] = args
			request.session.modified = True
			
	else:
		title=Db.objects.get(id = product_id).title

		if Db.objects.get(id = product_id).on_stock:
			price=Db.objects.get(id = product_id).stock_price
			
		else:
			price=Db.objects.get(id = product_id).price

		args.insert(0,title)
		args.insert(1,price)
		args.insert(2,int(form['number']))
		request.session.set_expiry(9999999) # от бaлды
		request.session['cart'] = { str(product_id) : args }
		request.session.modified = True
	print(str(request.session['cart']))

	return redirect('/main/cart') 

def index(request):
	dbs = Db.objects.order_by('-published')
	rubrics = Rubric.objects.all()	
	context = {'dbs': dbs, 'rubrics': rubrics}
	return render(request, 'main/index.html', context)
def stocks(request):
	dbs = Db.objects.filter(on_stock = True)
	rubrics = Rubric.objects.all()
	context = {'dbs': dbs, 'rubrics': rubrics}
	return render(request, 'main/stocks.html', context)
def about_us(request):
	rubrics = Rubric.objects.all()
	context = {'rubrics': rubrics}
	return render(request, 'main/about_us.html', context)
def basket(request):
	rubrics = Rubric.objects.all()
	context = {'rubrics': rubrics}
	return render(request, 'main/basket.html', context)
def cart(request):
	rubrics = Rubric.objects.all()
	dbs = Db.objects.all()
	try:
		sess = request.session['cart']
		isCart = True
	except:

		sess = ''
		isCart = False
		Id = []
		title = []
		price = []
		number = []
		totalPrice = 0
	if len(sess) == 0:
		isCart = False

	Id = []
	title = []
	price = []
	number = []
	LPrice = []
	nI = 0
	nT = 0
	nP = 0
	nN = 0
	nPL = 0
	totalPrice = 0
	for i in sess:
		Id.insert(nI,i)
		nI += 1

	for i in sess:
		title.insert(nT,str( sess[str(i)][0] ))
		nT += 1

	for i in sess:
		price.insert(nP,str( sess[str(i)][1] ))
		nP += 1

	for i in sess:
		number.insert(nN,str( sess[str(i)][2] ))
		nN += 1

	for i in price:
		LPrice.insert(nPL, str(float(i) * int(number[nPL])))
		nPL +=1

	FPrice = price



	for i in LPrice:
		totalPrice += float(i)

	context = {'isCart':isCart ,'totalPrice':totalPrice, 'rubrics': rubrics, 'sess':sess, 'dbs':dbs, 'Id':Id, 'title':title, 'FPrice':FPrice, 'LPrice':LPrice, 'number': number}
	return render(request, 'main/cart.html', context)

def plusNumber(request, product_id):
	form = request.POST
	sess = request.session['cart']

	sess[str(form['plus'])].insert(2, int(sess[str(form['plus'])][2]) + 1) 
	request.session.modified = True

	return redirect('/main/cart/')

def minusNumber(request, product_id):
	form = request.POST
	sess = request.session['cart']
	num = int(sess[str(form['minus'])][2]) - 1
	if num <= 0:
		delItem(request, product_id)
	else:

		sess[str(form['minus'])].insert(2,num ) 
		request.session.modified = True

	return redirect('/main/cart/')
def pay(request):
	rubrics = Rubric.objects.all()
	context = {'rubrics': rubrics}
	
	return render(request, 'main/pay.html', context)

NightFairy/main/templates/layout/basic.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>{% block title %}Ночная фея{% endblock %}</title>
		<link rel="icon"  href="{% static 'src/LogoFairy.jpeg' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

	</head>
	<body>

		<!-- Шапка -->
		<header class="head">
			<!--Корзина-->
			<a href="/main/cart/"><img id="box" alt="корзина" title="Корзина" src="{% static 'src/trollface.png' %}"></a>

			<!-- Лого и название -->
			<img src="{% static 'src/ColorNightFairy.png' %}" alt="Logo">
			<div class="title">
				<h1 class="name">Ночная фея</h1>
				<h1 class="tagline">Не купишь - отсосешь</h1>
			</div>
			
			<div id="head">
				<!-- Главное меню и тп -->
				<nav class="menu">						
					<a target="_blank"class="mymeny" id="main" href="{% url 'main:index' %}">главная</a>
					<a target="_blank"id="seals" class="mymeny" href="{% url 'main:stocks' %}">акции</a>
					<a target="_blank"class="mymeny" href="{% url 'main:about_us' %}">о нас</a>
				</nav>
				<!-- Как с нами связатся-->
				<nav class="NavMess">
					<a target="_blank"id="telega" title="Должен быть установлен Telegram для ПК или телефона"class="messanger" href="https://t.me/Basiiil_b">telegram </a>
					<a target="_blank"id="viber" title="Должен быть установлен Viber для ПК или для телефона" class="messanger" href="viber://chat?number=79170277769">viber </a>
					<a target="_blank"id="wt" title="Должен быть установлен WhatsApp для ПК или для телефона" class="messanger" href="https://wa.me/79170277769">whatsapp </a>
				</nav>
			</div>
			<div id="divLinks">
			{% for rubric in rubrics %}
				{% if current_rubric.name == rubric.name %}

					<a target="_blank"  href="/main/{{ rubric.pk }}"><button style="background-color: #BF7110 "  class="link">{{ rubric.name }}</button></a>
					
				{% else %}
					<a target="_blank"  href="/main/{{ rubric.pk }}"><button style="background-color: #000000 "  class="link">{{ rubric.name }}</button></a>
					
				{% endif %}
			{% endfor %}
		</div>
		</header>


		<section>
		<!-- Создаю окна продоваемых вещей-->
			{% block content %}
			{% endblock %}
		</section>
		
		<script src="{% static 'js/script.js' %}"></script>
	</body>
</html>

NightFairy/main/templates/main/about_us.html
{% extends "layout/basic.html" %}
{% load static %}
{% block title %} Ночная Фея || О нас{% endblock %}
{% block content %}
	<div class = "content">
		<h1 class="stuffDescription">О нас:</h1>
		<p class="stuffDescription">
What is Lorem Ipsum?

Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
Why do we use it?

It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).

Where does it come from?

Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.
	</p>
<br>
<h1 class="stuffDescription">Список наших лучших сотрудников возглавляет OWNER:</h1>

<img src="{% static 'src/chadd.jpg' %}">


<br><br><br><br>
<h2 class="stuffDescription">Вторым по списку идет Ибрагим Инцентремол (наш программист):<h2>
<img src="{% static 'src/incel.jpg' %}">
{% endblock %}
		

NightFairy/main/templates/main/by_rubric.html
{% extends 'layout/basic.html' %}
{% load static %}
<!-- Создаю окна продоваемых вещей-->
{% block title %} {{ current_rubric.name }} {% endblock %}
{% block content %}
<div class = content>
	{% for db in dbs %}
		<div class="stuff">
			<a href="{% url 'main:product' db.id %}" target="_blank">
				<div class="img_cont">
					<img class="stuffImg" src="{% static db.img_name %}">
				</div>

				<h2 class="stuffDescription">{{ db.title }}</h2>
				<p class="stuffDescription">{{ db.content }}</p>
						
				<p class="stuffDescription">Раздел: <i><a target = "_blank"  href="{% url 'main:by_rubric' db.rubric.pk %}">{{ db.rubric.name }}</a></i></p>
						
				{% if db.on_stock %}

					<div class="prices_frame">
						<s class="strike_price"><p class = "price">Цена: {{ db.price }}р</p></s>
						<p class = "price_on_stock" >{{ db.stock_price }}р</p>
					</div>
						
						
				{% else %}
					<p class = "price">Цена: {{ db.price }}р</p>
				{% endif %}
			</a>
					
		</div>
	{% endfor %}
</div>
{% endblock %}		


NightFairy/main/templates/main/cart.html
{% extends "layout/basic.html" %}
{% load static %}
{% block title %} Ночная Фея || Корзина {% endblock %}
{% block content %}
	<div class="Cart" id="content">
		<h1 class="H1Cart" align="center">Корзина</h1>
		<div class="CartContent">
			{% if isCart %}
				<div class="divTitle">
					<h2>Название:</h2>
					<br>
					{% for i in title %}
						<h2>{{i}}</h2>
						<hr>
					{% endfor %}

				</div>
				<div class="divPriceNumber">
					<h2>Цена за шт:</h2>
					<br>
					{% for i in FPrice %}
						<h2>{{i}}</h2>
						<hr>
					{% endfor %}

				</div>

				<div class="divPriceNumber">
					<h2>Кол-во:</h2>
					<br>
					{% for i in number %}
						<h2 class="PriceBeforBTn">{{i}}</h2>
						<hr>
					{% endfor %}
				</div>
				<div class="divPriceNumber">
					<h1>Изменить:</h1>
					<div style="margin-top: 14px; margin-left: -20px;">
						{% for i in Id %}													
							<h1></h1>
							<form method="post" action="/main/product/{{ i }}/plus/" style="float: left;">
								{% csrf_token %}
								<input class="PMBtn " type="submit" name="{{ i }}" value="+">
								<input type="hidden" name="plus" value="{{ i }}">
								
							</form>
							<form method="post" action="/main/product/{{ i }}/minus/">
								{% csrf_token %}
								<input class="PMBtn MinusBtn" type="submit" name="{{ i }}" value="-">
								<input type="hidden" name="minus" value="{{ i }}">

								
							</form>	
							<hr>																		
						{% endfor %}
					</div>
				</div>


				<div class="divPriceNumber">
					<h2>Цена:</h2>
					<br>
					{% for i in LPrice %}
						<h2>{{i}}</h2>
						<hr>
					{% endfor %}

				</div>
				<div class="divPriceNumber">
					<h2>Удалить:</h2>
					<div style="    margin-top: 14px;">
						{% for i in Id %}
						<form method="post" action="/main/product/{{ i }}/del/">
									{% csrf_token %}
									<input class="PMBtn MinusBtn" type="submit" name="{{ i }}" value="X">
									<input type="hidden" name="del" value="{{ i }}">			
						</form>
						<hr>
						{% endfor %}
					</div>
					
				</div>

				
				<div style="display: table-row;">
					<h2 style="    font-size: 29px; float: left;" >Итого:</h2><h3 style="float: right; display: inline-block; font-size: 25px;" >{{ totalPrice }}р</h3>
				</div>
				<br>
				<div>
					<form method="post", action="/main/pay/">
						{% csrf_token %}
						<input type="submit" name="pay" class="PayBtn" value="Оплатить">
						
					</form>
					
				</div>
				
			{% else %}
			
				<h1>Корзина пуста</h1>
			{% endif %}
		</div>
	</div>
{% endblock %}
		

NightFairy/main/templates/main/create.html
{% extends "layout/basic.html" %}

{% block title %} {{ current_rubric.name }} {% endblock %}

{% block content %}


<div class="comments"> 
	<h1 class="stuffDescription">Добавление обьявлений</h1>
	<div>


	<form class = "stuffDescription"method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Добавить">
	</form>
</div>
{% endblock %}

NightFairy/main/templates/main/index.html
{% extends "layout/basic.html" %}
{% load static %}
{% block content %}
	<div class = content>
		{% for db in dbs %}
			<div class="stuff">
				<a href="{% url 'main:product' db.id %}" target="_blank">
					<div class="img_cont">
						<img class="stuffImg" src="{% static db.img_name %}">
					</div>
					
					<h2 class="stuffDescription">{{ db.title }}</h2>
					<p class="stuffDescription">{{ db.content }}</p>
					<p class="stuffDescription">Раздел: <i><a target = "_blank"  href="{% url 'main:by_rubric' db.rubric.pk %}">{{ db.rubric.name }}</a></i></p>
					{% if db.on_stock %}

						<div class="prices_frame">
							<s class="strike_price"><p class = "price">Цена: {{ db.price }}р</p></s>
							<p class = "price_on_stock" >{{ db.stock_price }}р</p>
						</div>
						
						
					{% else %}
						<p class = "price">Цена: {{ db.price }}р</p>
					{% endif %}
				</a>
						
			</div>
		{% endfor %}
	</div>
{% endblock %}
		

NightFairy/main/templates/main/pay.html
{% extends "layout/basic.html" %}
{% load static %}
{% block title %} Ночная Фея || Корзина {% endblock %}
{% block content %}
	<div class="content" id="content">
		
	</div>
{% endblock %}
		

NightFairy/main/templates/main/product.html
{% extends 'layout/basic.html' %}
{% load static %}
<!-- Создаю окна продоваемых вещей-->
{% block title %} {{ db.title}} {% endblock %}
{% block content %}
	<div class = content id="content">

		<div class="stuff"  >

				<div class="img_cont">
					<img class="stuffImg" src="{% static db.img_name %}">
				</div>
				<h2 class="stuffDescription" id = "product_title">{{ db.title }}</h2>
				<h2 class="stuffDescription">Описание:</h2><p class="stuffDescription">{{ db.full_content }}</p>

				<p class="stuffDescription">Раздел: <i><a target = "_blank"  href="{% url 'main:by_rubric' db.rubric.pk %}">{{ db.rubric.name }}</a></i></p>

				{% if db.on_stock %}

					<div class="prices_frame">
						<s class="strike_price" ><p class = "price">Цена: {{ db.price }}р</p></s>
						<p class = "price_on_stock" id="strike_price">{{ db.stock_price }}р</p>
					</div>


				{% else %}

					<p class = "price" >Цена: <p class="price" id="price">{{ db.price }}р</p>
				{% endif %}
				<!--<input type="hidden" id ="product_desc" value="{{ db.content }}">
				<input type="hidden" id ="number" value="0">  Не знаю зачем это вообще нужно, но вреде и без этого все работает -->



		</div>
		<div class="buyPutFrame">
			<form method="post" action="/main/product/{{ db.id }}/addToCart/" >
				{% csrf_token %}
				<input type="submit" class = "buyBtn" id="addToBasket" value="Добавить в корзину" >
				<br><br>
			
				<input type="hidden" name="product_id" value="{{ db.id }}">
				<input id ="number" type="hidden" name="number" value="1">
				<input type="button"id = "increaseNumber" style="margin-bottom: 10px; "class="buyBtn" value="&#708";><br>
				<output  style="margin-left: 30px;" id="ong"  >1</output><br>
				<input type="button"id = 'decreaseNumber' style="margin-top: 10px; ;"class="buyBtn" value="&#709";>



			</form>

		</div>


	</div>

{% endblock %}

NightFairy/main/templates/main/stocks.html
{% extends "layout/basic.html" %}
{% load static %}
{% block title %} Ночная Фея || Акции {% endblock %}
{% block content %}
	<div class = content>
		{% for db in dbs %}
			<div class="stuff">
				<a href="{% url 'main:product' db.id %}" target="_blank">
					<div class="img_cont">
						<img class="stuffImg" src="{% static db.img_name %}">
					</div>
					<h2 class="stuffDescription">{{ db.title }}</h2>
					<p class="stuffDescription">{{ db.content }}</p>
					<p class="stuffDescription">Раздел: <i><a target = "_blank"  href="{% url 'main:by_rubric' db.rubric.pk %}">{{ db.rubric.name }}</a></i></p>
					{% if db.on_stock %}

						<div class="prices_frame">
							<s class="strike_price"><p class = "price">Цена: {{ db.price }}р</p></s>
							<p class = "price_on_stock" >{{ db.stock_price }}р</p>
						</div>
						
						
					{% else %}
						<p class = "price">Цена: {{ db.price }}р</p>
					{% endif %}
				</a>
						
			</div>
		{% endfor %}
	</div>
{% endblock %}
		